# meta-openxt-domains — NDVM, USBVM, SyncVM service domains
BBPATH .= ":${LAYERDIR}"

BBFILES += " \
    ${LAYERDIR}/recipes-*/*/*.bb \
    ${LAYERDIR}/recipes-*/*/*.bbappend \
    ${LAYERDIR}/recipes-*/*/*/*.bb \
    ${LAYERDIR}/recipes-*/*/*/*.bbappend \
"

BBFILE_COLLECTIONS += "openxt-domains"
BBFILE_PATTERN_openxt-domains := "^${LAYERDIR}/"
BBFILE_PRIORITY_openxt-domains = "10"

LAYERVERSION_openxt-domains = "1"
LAYERSERIES_COMPAT_openxt-domains = "dunfell"

LAYERDEPENDS_openxt-domains = " \
    openxt-base \
    networking-layer \
"

LAYERDESCRIPTION_openxt-domains = "OpenXT service domain images: NDVM, USBVM, SyncVM"

require ${LAYERDIR}/conf/distro/include/openxt-domains.inc
